"""
Pydantic models for Comic Strip Generation
"""

from typing import List, Optional, Literal
from pydantic import BaseModel, Field


class ComicPanel(BaseModel):
    """Single comic book panel"""
    panel_number: int = Field(..., description="Panel number in sequence (1-3)")
    shot_type: Literal["wide", "medium", "close-up", "extreme-close-up", "establishing"] = Field(
        ..., description="Camera shot type for the panel"
    )
    action_description: str = Field(..., description="What happens in this panel")
    character_focus: List[str] = Field(default_factory=list, description="Characters visible in panel")
    location: str = Field(..., description="Where the panel takes place")
    dialogue: Optional[str] = Field(None, description="Dialogue or caption text")
    sound_effects: Optional[str] = Field(None, description="Onomatopoeia (POW!, BANG!, etc)")
    emotional_tone: str = Field(..., description="Mood/emotion of the panel")
    
    # Generated by stripper agent
    enhanced_prompt: Optional[str] = Field(None, description="Art-style enhanced prompt for image generation")


class ComicPage(BaseModel):
    """Single page containing 3 panels"""
    page_number: int = Field(..., description="Page number in the comic")
    scene_title: str = Field(..., description="Title/summary of this scene")
    panels: List[ComicPanel] = Field(..., min_items=1, max_items=3, description="1-3 panels per page")
    art_style: str = Field(default="Noir Comic Book Style", description="Art style for this page")
    color_palette: Optional[str] = Field(None, description="Color scheme description")


class CharacterSheet(BaseModel):
    """Character reference for consistent generation"""
    name: str = Field(..., description="Character name")
    physical_description: str = Field(..., description="Detailed physical appearance")
    clothing: str = Field(..., description="Typical clothing/costume")
    personality_traits: List[str] = Field(..., description="Key personality traits")
    role: str = Field(..., description="Role in story (detective, killer, victim, etc)")
    
    # Generated reference image
    reference_image_prompt: Optional[str] = Field(None, description="Prompt for character reference generation")
    reference_image_path: Optional[str] = Field(None, description="Path to generated reference image")


class ComicStripStoryboard(BaseModel):
    """Complete comic strip storyboard"""
    title: str = Field(..., description="Comic strip title")
    genre: Literal["detective", "noir", "cyberpunk", "fantasy", "horror", "satire"] = Field(
        ..., description="Story genre"
    )
    default_art_style: str = Field(default="Noir Comic Book Style", description="Default art style")
    
    # Characters
    characters: List[CharacterSheet] = Field(..., description="All characters in the story")
    
    # Story structure
    pages: List[ComicPage] = Field(..., description="Comic pages with panels")
    
    # Metadata
    total_panels: int = Field(..., description="Total number of panels")
    estimated_reading_time: str = Field(..., description="Estimated reading time")
    
    class Config:
        json_schema_extra = {
            "example": {
                "title": "The Midnight Murder",
                "genre": "detective",
                "default_art_style": "Noir Comic Book Style",
                "characters": [
                    {
                        "name": "Detective Morgan",
                        "physical_description": "Tall, weathered face, sharp eyes, graying hair",
                        "clothing": "Trench coat, fedora, worn suit",
                        "personality_traits": ["cynical", "observant", "determined"],
                        "role": "detective"
                    }
                ],
                "pages": [
                    {
                        "page_number": 1,
                        "scene_title": "Discovery of the Body",
                        "art_style": "Noir Comic Book Style",
                        "panels": [
                            {
                                "panel_number": 1,
                                "shot_type": "establishing",
                                "action_description": "Rain-soaked alley at night",
                                "character_focus": [],
                                "location": "Dark alley",
                                "dialogue": "The city never sleeps...",
                                "emotional_tone": "ominous"
                            }
                        ]
                    }
                ],
                "total_panels": 3,
                "estimated_reading_time": "5 minutes"
            }
        }
