#!/bin/sh

cd /app
. .venv/bin/activate

exec uvicorn cinema.server.app:app --host 0.0.0.0 --port 8000 2>&1
# exec uvicorn cinema.server.app:app --host 0.0.0.0 --port 8000 > /app/output/server.log 2>&1
